steer_bot_hardware_gazebo:
    rear_wheel  : 'base_to_wheel'
    front_steer : 'base_to_steer'
    virtual_rear_wheels  : ['base_to_right_rear_wheel', 'base_to_left_rear_wheel']
    virtual_front_wheels : ['base_to_right_front_wheel', 'base_to_left_front_wheel']
    virtual_front_steers : ['base_to_right_front_steer', 'base_to_left_front_steer']

    # ackermann link mechanism
    enable_ackermann_link: 1
    wheel_separation_w : 0.5
    wheel_separation_h : 0.79
