recovery_behaviour_enabled: true

recovery_behaviors:
  - {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
  - {name: step_back_and_max_steer_recovery, type: step_back_and_max_steer_recovery/StepBackAndMaxSteerRecovery}
  - {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}

step_back_and_max_steer_recovery:
    trial_times         : 3
    # back
    linear_vel_back     : -0.3
    duration_back       : 3.0
    # steer
    linear_vel_steer   : 0.3
    angular_vel_steer  : 0.5
    duration_steer     : 2.0
    # forward
    linear_vel_forward   : 0.3
    duration_forward     : 3.0
